# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_project_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkflowModel',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Data')),
                ('script', models.TextField(verbose_name=b'DSL Script')),
            ],
            bases=('project.data',),
        ),
    ]
