# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScmGitModel',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Data')),
                ('url', models.URLField()),
                ('branch', models.CharField(max_length=60)),
            ],
            bases=('project.data',),
        ),
    ]
