# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 15:13
from __future__ import unicode_literals

from django.db import migrations
import multipleselection.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nodes',
            field=multipleselection.models.MultipleSelectionField(choices=[('any', 'Any'), ('ppc64le_debian_jessie', 'ppc64le/debian:jessie'), ('ppc64le_ubuntu_16_04', 'ppc64le/ubuntu:16.04')], default='any', max_length=150),
            preserve_default=False,
        ),
    ]
