# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_project_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTravisModel',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Data')),
                ('url', models.URLField(verbose_name=b'Repository URL')),
                ('branch', models.CharField(max_length=60)),
            ],
            bases=('project.data',),
        ),
    ]
