# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='shortName',
            field=models.CharField(max_length=20, unique=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
