# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20160714_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='token',
        ),
        migrations.AddField(
            model_name='node',
            name='token',
            field=models.CharField(default=b'257316da86d8a20c019ed810dab7b9d0c6967d30', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.URLField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='node',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
