# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20160719_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
