# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160720_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
