# Copyright IBM Corp, 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

FROM ppc64le/debian:jessie
MAINTAINER Davi Diorio Mendes <ddiorio@br.ibm.com>

USER root

RUN groupadd -g 1000 {{ ssh_user }} \
    && useradd -d /home/{{ ssh_user }} -u 1000 -g 1000 -m -s /bin/bash {{ ssh_user }}

RUN apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew"  --no-install-recommends \
        gearman-job-server \
        openssh-server \
        iptables \
        sudo

COPY iptables_setup.sh /root/iptables_setup.sh
COPY entrypoint.sh /root/entrypoint.sh

RUN mkdir -p /home/{{ ssh_user }}/.ssh && \
    chown -R {{ ssh_user }}:{{ ssh_user }} /home/{{ ssh_user }}; \
    echo "{{ ssh_user }} ALL=(root) NOPASSWD: ALL" > /etc/sudoers; \
    chmod +x /root/iptables_setup.sh; \
    chmod +x /root/entrypoint.sh

COPY authorized_keys /home/{{ ssh_user }}/.ssh/authorized_keys

EXPOSE 4730

CMD ["bash", "/root/entrypoint.sh"]

# vim:set ft=dockerfile:
